In [1]:
import numpy as np

In [2]:
new_ar = np.array([1,2,3,4,5])
print(new_ar)

[1 2 3 4 5]


In [3]:
type(new_ar)

numpy.ndarray

In [4]:
new_ar.ndim

1

In [5]:
two_di=np.array([[1,3,5,7,9],[2,4,6,8,10]])
print(two_di)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [6]:
two_di.ndim

2

In [7]:
two_di.size

10

In [8]:
two_di.shape

(2, 5)

In [9]:
two_di.dtype #datatype

dtype('int32')

In [11]:
mx = np.array([[1,2,3,4,5],[11,22,33,44,55],[10,20,30,40,50]])
print(mx)

[[ 1  2  3  4  5]
 [11 22 33 44 55]
 [10 20 30 40 50]]


In [17]:
auto = np.ones(10)
print(auto)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [18]:
auto.dtype

dtype('float64')

In [22]:
auto_1 = np.ones((10,5))
print(auto_1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
mx_ms = np.ones((3,5), dtype= int)
print(mx_ms)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
mx_zero= np.zeros((3,7), dtype=int)
print(mx_zero)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [26]:
mx_zero.dtype

dtype('int32')

In [27]:
mx_n = np.ones((2,5), dtype=bool)
print(mx_n)

[[ True  True  True  True  True]
 [ True  True  True  True  True]]


In [30]:
mx_t = np.zeros((4,7), dtype=bool)
print(mx_t)

[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]]


In [31]:
mx_e=np.empty((3,6))
print(mx_e)

[[1.37962049e-306 1.24610791e-306 1.11260959e-306 1.69109959e-306
  9.34603679e-307 1.42419802e-306]
 [1.78019082e-306 4.45061456e-308 1.24612081e-306 1.37962049e-306
  9.34597567e-307 1.29061821e-306]
 [1.78019625e-306 1.11255866e-306 8.90098127e-307 9.34609790e-307
  3.91792279e-317 0.00000000e+000]]
