In [4]:
import numpy as np

In [5]:
new_ar = np.array([1,2,3,4,5])
print(new_ar)

[1 2 3 4 5]


In [6]:
type(new_ar)

numpy.ndarray

In [7]:
new_ar.ndim

1

In [10]:
two_di=np.array([[1,3,5,7,9],[2,4,6,8,10]])
print(two_di)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [11]:
two_di.ndim

2

In [12]:
two_di.size

10

In [13]:
two_di.shape

(2, 5)

In [14]:
two_di.dtype #datatype

dtype('int32')